services:
  mariadb:
    image: mariadb:latest
    environment:
      #change in prod
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    networks:
      - default
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    environment:
      #change in prod
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    restart: unless-stopped
    networks:
      - default

  main:
    build:
      context: .
      dockerfile: ./docker/main/Dockerfile
    restart: unless-stopped
    ports:
      - "80:8080"
    networks:
      - default
      - cloudflare-net
    volumes:
      - ./.git:/app/.git:ro
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      GIN_MODE: ${GIN_MODE}
    init: true

volumes:
  mariadb_data:

networks:
  default:
    driver: bridge
  cloudflare-net:
    external: true

